### ISSUE TITLE
KeyError: 'sizeX'

### ISSUE THREAD

**Issue by ccalby** [vvaezian/metabase_api_python#41]
When running the mb.copy_collection command, 

> Copying the dashboard "Report" ...
> Traceback (most recent call last):
>   File "/root/./copy_metabase_reports.py", line 5, in <module>
>     mb.copy_collection(source_collection_id=5, destination_parent_collection_id=11, deepcopy_dashboards=True, verbose=True)
>   File "/usr/local/lib/python3.10/dist-packages/metabase_api/metabase_api.py", line 931, in copy_collection
>     self.copy_dashboard(source_dashboard_id=dashboard_id,
>   File "/usr/local/lib/python3.10/dist-packages/metabase_api/metabase_api.py", line 838, in copy_dashboard
>     card_json[prop] = card[prop]
> KeyError: 'sizeX'
> root@localhost:~#

**Comment by vvaezian** [comment]
Hi @ccalby. This error is due to a [change](https://github.com/metabase/metabase/issues/16344) introduced in v.45 of Metabase. 
I'll fix this for the Python wrapper once the version [v.45.2](https://github.com/metabase/metabase/milestone/170?closed=1) of Metabase is released (as it fixes quite a few issues).
In the meantime, to fix the error on your end, you can replace `sizeX` and `sizeY` in the source code with `size_x` and `size_y`.

**Comment by noahtf13** [comment]
Is this fixed? I'm still getting the issue. Thanks for the hard work @vvaezian

**Comment by vvaezian** [comment]
Fixed in version 0.2.15.

**Comment by noahtf13** [comment]
Amazing, thank you!

**Comment by vvaezian** [comment]
Hi @ccalby and @noahtf13,

At Intellimenta we have developed [DataBot](https://intellimenta.com/products/databot/), a conversational analytics app that connects with **Metabase** and enables users to ask questions about data and visualize the results using natural language in their preferred language.
If your company uses Metabase, DataBot can significantly enhance how your team and customers interact with data. If you're interested in learning more, you can book a demo using [this](https://outlook.office365.com/owa/calendar/booking@intellimenta.com/bookings/s/ZEMZuuM07U6C4Tr-GKUyOQ2) link. Happy to discuss further.
